[[block]]
block="pomodoro"
use_nag=true
[[block]]
block="temperature"
collapsed=false
format="{average}"
[[block]]
block="uptime"
[[block]]
block="cpu"
format = "{barchart} {utilization}% {frequency}GHz"
[[block]]
block="net"
use_bits=true
format = "{ip} {speed_down} {speed_up}"
[[block]]
block="sound"
[[block]]
block="battery"
format="{time} {percentage}%"
[[block]]
block="time"
format="%d/%m %a %I:%M %P"
